# Building basic functions with numpy
Numpy is the main package for scientific computing in Python. It is maintained by a large community (www.numpy.org). In this exercise you will learn several key numpy functions such as np.exp, np.log, and np.reshape. You will need to know how to use these functions for future assignments.

## sigmoid function,np.exp()
**Exercise:** Build a function that returns the sigmoid of a real number x. Use math.exp(x) for the exponential function.

**Reminder:**
$$sigmoid(x) = \frac{1}{1+e^{-x}}$$is sometimes also known as the logistic function. It is a non-linear function used not only in Machine Learning (Logistic Regression), but also in Deep Learning.
![sigmoid](./Image/sigmoid.png)
To refer to a function belonging to a specific package you could call it using package_name.function(). Run the code below to see an example with math.exp().

In [1]:
import math

def basic_sigmoid(x):
    s=1.0/(1+1/math.exp(x))
    return s 

In [2]:
basic_sigmoid(3)

0.9525741268224334

Actually, we **rarely** use the “math” library in deep learning because the inputs of the functions are **real numbers**. In deep learning we mostly use matrices and vectors. This is why **numpy** is more useful.

In [4]:
### One reason why we use "numpy" instead of "math" in Deep Learning ###
x = [1, 2, 3]
#basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.

In fact, if $$x = (x_1, x_2, ..., x_n)$$ is a row vector then np.exp(x) will apply the exponential function to every element of x. The output will thus be: $$np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})$$


In [5]:
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


Furthermore,if x is a vector,then a python operation such as $$s = x+3$$ or $$ s =\frac {1}{x}$$will output s as a vector of the same size as x. This is called broadcast in python

In [6]:
x = np.array([1,2,3])
print(x+5)

[6 7 8]


**Exercise:** Implement the sigmoid function using numpy.

**Instructions:** x could now be either a real number, a vector, or a matrix. The data structures we use in numpy to represent these shapes (vectors, matrices…) are called numpy arrays. You don’t need to know more for now. 
$$\text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1}$$


In [7]:
import numpy as np
def sigmoid(x):
    s = 1.0/(1.0+1.0/np.exp(x))
    return s 

In [8]:
x = np.array([1,23,3])
sigmoid(x)

array([0.73105858, 1.        , 0.95257413])

## Sigmoid gradient
**Exercise:**Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is:
$$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$
You often code this function in two steps: 
1. Set s to be the sigmoid of x. You might find your sigmoid(x) function useful. 
2. Compute σ′(x)=s(1−s)

In [9]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    ds = s*(1-s)
    return ds

In [10]:
x = np.array([1,2,3])
print("sgmoid_derivative(x)="+str(sigmoid_derivative(x)))

sgmoid_derivative(x)=[0.19661193 0.10499359 0.04517666]


## Reshape arrays
Two common numpy functions used in deep learning are np.shape and np.reshape(). 
- X.shape is used to get the shape (dimension) of a matrix/vector X. 
- X.reshape(…) is used to reshape X into some other dimension.

For example, in computer science, an image is represented by a 3D array of shape (length,height,depth=3)(length,height,depth=3). However, when you read an image as the input of an algorithm you convert it to a vector of shape (length∗height∗3,1)(length∗height∗3,1). In other words, you **“unroll”**, or reshape, the 3D array into a 1D vector.